version: "3"
services:
  strfry:
    container_name: strfry
    image: dockurr/strfry:latest
    environment:
            STREAMS: "relayable.org,relay.damus.io"
    ports:
        - 7777:7777
    volumes:
        - /path/to/strfry-db:/app/strfry-db
        - /path/to/strfry.conf:/etc/strfry.conf
